### ISSUE TITLE
Repository is missing

### ISSUE THREAD

**Issue by ShaneCurcuru** [floss-foundations/npo-public-filings#1]
I have been working on a FLOSS foundations directory project, including financial data, and have a local clone of this repository - but now when I come back to GitHub, it's gone!

Why was this repository deleted / emptied?

**Comment by ShaneCurcuru** [comment]
Never mind - searching brought me here, instead of actually looking at the cool GitLab site that actually houses this repository.  Curious if the owners here are the same as the owners there...

**Comment by tbm** [comment]
The reason it moved is because GitHub has filesize restrictions (100 MB) and the IRS downloads were too large.

I think it's controlled by the same people.  I haven't made any updates recently.  Contributions are welcome.  I can give you access on GitLab if you want.
